
name: d3fiant security
description: A little learning is a dangerous thing
url: d3fiant.io
#permalink: /blog/:year/:month/:day/:title

# Theme Settings
theme: jekyll-theme-tactile

# Build settings
#markdown: kramdown
permalink: pretty



defaults:
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"
