theme: jekyll-theme-tactile

name: d3fiant security
description: A little learning is a dangerous thing
url: d3fiant.io
permalink: /blog/:year/:month/:day/:title


defaults:
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"
