theme: jekyll-theme-tactile

name: d3fiant security
description: A little learning is a dangerous thing
permalink: /blog/:year/:month/:day/:title


defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"
