theme: jekyll-theme-slate

name: d3fiant.io
description: Cybersecurity professional with a focus on adversarial simulation. Love for red teaming, reversing, and general learning.
permalink: /blog/:year/:month/:day/:title
